export interface Airport {
  iata: string;
  name: string;
  city: string;
  country: string;
  lat: number;
  lng: number;
}

export const AIRPORTS: Airport[] = [
  { iata: "JFK", name: "John F. Kennedy International", city: "New York", country: "US", lat: 40.6413, lng: -73.7781 },
  { iata: "LAX", name: "Los Angeles International", city: "Los Angeles", country: "US", lat: 33.9425, lng: -118.4081 },
  { iata: "ORD", name: "O'Hare International", city: "Chicago", country: "US", lat: 41.9742, lng: -87.9073 },
  { iata: "ATL", name: "Hartsfield-Jackson Atlanta International", city: "Atlanta", country: "US", lat: 33.6407, lng: -84.4277 },
  { iata: "DFW", name: "Dallas/Fort Worth International", city: "Dallas", country: "US", lat: 32.8998, lng: -97.0403 },
  { iata: "DEN", name: "Denver International", city: "Denver", country: "US", lat: 39.8561, lng: -104.6737 },
  { iata: "SFO", name: "San Francisco International", city: "San Francisco", country: "US", lat: 37.6213, lng: -122.379 },
  { iata: "SEA", name: "Seattle-Tacoma International", city: "Seattle", country: "US", lat: 47.4502, lng: -122.3088 },
  { iata: "MIA", name: "Miami International", city: "Miami", country: "US", lat: 25.7959, lng: -80.2870 },
  { iata: "BOS", name: "Logan International", city: "Boston", country: "US", lat: 42.3656, lng: -71.0096 },
  { iata: "LHR", name: "Heathrow", city: "London", country: "GB", lat: 51.4775, lng: -0.4614 },
  { iata: "LGW", name: "Gatwick", city: "London", country: "GB", lat: 51.1537, lng: -0.1821 },
  { iata: "CDG", name: "Charles de Gaulle", city: "Paris", country: "FR", lat: 49.0097, lng: 2.5479 },
  { iata: "AMS", name: "Amsterdam Airport Schiphol", city: "Amsterdam", country: "NL", lat: 52.3086, lng: 4.7639 },
  { iata: "FRA", name: "Frankfurt Airport", city: "Frankfurt", country: "DE", lat: 50.0379, lng: 8.5622 },
  { iata: "MAD", name: "Adolfo Suárez Madrid-Barajas", city: "Madrid", country: "ES", lat: 40.4983, lng: -3.5676 },
  { iata: "BCN", name: "Barcelona-El Prat", city: "Barcelona", country: "ES", lat: 41.2974, lng: 2.0833 },
  { iata: "FCO", name: "Leonardo da Vinci–Fiumicino", city: "Rome", country: "IT", lat: 41.8003, lng: 12.2389 },
  { iata: "MXP", name: "Milan Malpensa", city: "Milan", country: "IT", lat: 45.6306, lng: 8.7281 },
  { iata: "ZRH", name: "Zurich Airport", city: "Zurich", country: "CH", lat: 47.4647, lng: 8.5492 },
  { iata: "VIE", name: "Vienna International Airport", city: "Vienna", country: "AT", lat: 48.1103, lng: 16.5697 },
  { iata: "BRU", name: "Brussels Airport", city: "Brussels", country: "BE", lat: 50.9010, lng: 4.4844 },
  { iata: "CPH", name: "Copenhagen Airport", city: "Copenhagen", country: "DK", lat: 55.6180, lng: 12.6508 },
  { iata: "ARN", name: "Stockholm Arlanda Airport", city: "Stockholm", country: "SE", lat: 59.6519, lng: 17.9186 },
  { iata: "HEL", name: "Helsinki Airport", city: "Helsinki", country: "FI", lat: 60.3172, lng: 24.9633 },
  { iata: "OSL", name: "Oslo Airport Gardermoen", city: "Oslo", country: "NO", lat: 60.1939, lng: 11.1004 },
  { iata: "LIS", name: "Lisbon Portela Airport", city: "Lisbon", country: "PT", lat: 38.7742, lng: -9.1342 },
  { iata: "ATH", name: "Athens International Airport", city: "Athens", country: "GR", lat: 37.9364, lng: 23.9445 },
  { iata: "IST", name: "Istanbul Airport", city: "Istanbul", country: "TR", lat: 41.2753, lng: 28.7519 },
  { iata: "DXB", name: "Dubai International Airport", city: "Dubai", country: "AE", lat: 25.2532, lng: 55.3657 },
  { iata: "DOH", name: "Hamad International Airport", city: "Doha", country: "QA", lat: 25.2731, lng: 51.6082 },
  { iata: "AUH", name: "Abu Dhabi International Airport", city: "Abu Dhabi", country: "AE", lat: 24.4430, lng: 54.6511 },
  { iata: "SIN", name: "Singapore Changi Airport", city: "Singapore", country: "SG", lat: 1.3644, lng: 103.9915 },
  { iata: "HKG", name: "Hong Kong International Airport", city: "Hong Kong", country: "HK", lat: 22.3080, lng: 113.9185 },
  { iata: "NRT", name: "Narita International Airport", city: "Tokyo", country: "JP", lat: 35.7720, lng: 140.3929 },
  { iata: "HND", name: "Haneda Airport", city: "Tokyo", country: "JP", lat: 35.5494, lng: 139.7798 },
  { iata: "ICN", name: "Incheon International Airport", city: "Seoul", country: "KR", lat: 37.4691, lng: 126.4505 },
  { iata: "PEK", name: "Beijing Capital International Airport", city: "Beijing", country: "CN", lat: 40.0799, lng: 116.6031 },
  { iata: "PVG", name: "Shanghai Pudong International Airport", city: "Shanghai", country: "CN", lat: 31.1443, lng: 121.8083 },
  { iata: "BKK", name: "Suvarnabhumi Airport", city: "Bangkok", country: "TH", lat: 13.6900, lng: 100.7501 },
  { iata: "KUL", name: "Kuala Lumpur International Airport", city: "Kuala Lumpur", country: "MY", lat: 2.7456, lng: 101.7099 },
  { iata: "CGK", name: "Soekarno–Hatta International Airport", city: "Jakarta", country: "ID", lat: -6.1256, lng: 106.6559 },
  { iata: "SYD", name: "Sydney Airport", city: "Sydney", country: "AU", lat: -33.9399, lng: 151.1753 },
  { iata: "MEL", name: "Melbourne Airport", city: "Melbourne", country: "AU", lat: -37.6690, lng: 144.8410 },
  { iata: "AKL", name: "Auckland Airport", city: "Auckland", country: "NZ", lat: -37.0082, lng: 174.7850 },
  { iata: "GRU", name: "São Paulo–Guarulhos International Airport", city: "São Paulo", country: "BR", lat: -23.4356, lng: -46.4731 },
  { iata: "EZE", name: "Ministro Pistarini International Airport", city: "Buenos Aires", country: "AR", lat: -34.8222, lng: -58.5358 },
  { iata: "BOG", name: "El Dorado International Airport", city: "Bogotá", country: "CO", lat: 4.7016, lng: -74.1469 },
  { iata: "LIM", name: "Jorge Chávez International Airport", city: "Lima", country: "PE", lat: -12.0219, lng: -77.1143 },
  { iata: "SCL", name: "Arturo Merino Benítez International Airport", city: "Santiago", country: "CL", lat: -33.3930, lng: -70.7858 },
  { iata: "MEX", name: "Mexico City International Airport", city: "Mexico City", country: "MX", lat: 19.4363, lng: -99.0721 },
  { iata: "YYZ", name: "Toronto Pearson International Airport", city: "Toronto", country: "CA", lat: 43.6772, lng: -79.6306 },
  { iata: "YVR", name: "Vancouver International Airport", city: "Vancouver", country: "CA", lat: 49.1967, lng: -123.1815 },
  { iata: "YUL", name: "Montréal–Trudeau International Airport", city: "Montreal", country: "CA", lat: 45.4706, lng: -73.7408 },
  { iata: "JNB", name: "O.R. Tambo International Airport", city: "Johannesburg", country: "ZA", lat: -26.1367, lng: 28.2411 },
  { iata: "CAI", name: "Cairo International Airport", city: "Cairo", country: "EG", lat: 30.1219, lng: 31.4056 },
  { iata: "NBO", name: "Jomo Kenyatta International Airport", city: "Nairobi", country: "KE", lat: -1.3192, lng: 36.9275 },
  { iata: "ADD", name: "Addis Ababa Bole International Airport", city: "Addis Ababa", country: "ET", lat: 8.9779, lng: 38.7993 },
  { iata: "CMN", name: "Mohammed V International Airport", city: "Casablanca", country: "MA", lat: 33.3675, lng: -7.5900 },
  { iata: "MUM", name: "Chhatrapati Shivaji Maharaj International Airport", city: "Mumbai", country: "IN", lat: 19.0896, lng: 72.8656 },
  { iata: "DEL", name: "Indira Gandhi International Airport", city: "Delhi", country: "IN", lat: 28.5562, lng: 77.1000 },
  { iata: "BOM", name: "Chhatrapati Shivaji Maharaj International", city: "Mumbai", country: "IN", lat: 19.0896, lng: 72.8656 },
  { iata: "MNL", name: "Ninoy Aquino International Airport", city: "Manila", country: "PH", lat: 14.5086, lng: 121.0197 },
  { iata: "TPE", name: "Taiwan Taoyuan International Airport", city: "Taipei", country: "TW", lat: 25.0777, lng: 121.2327 },
  { iata: "VNO", name: "Vilnius Airport", city: "Vilnius", country: "LT", lat: 54.6341, lng: 25.2858 },
  { iata: "WAW", name: "Warsaw Chopin Airport", city: "Warsaw", country: "PL", lat: 52.1657, lng: 20.9671 },
  { iata: "PRG", name: "Václav Havel Airport Prague", city: "Prague", country: "CZ", lat: 50.1008, lng: 14.2600 },
  { iata: "BUD", name: "Budapest Ferenc Liszt International Airport", city: "Budapest", country: "HU", lat: 47.4298, lng: 19.2611 },
  { iata: "OTP", name: "Henri Coandă International Airport", city: "Bucharest", country: "RO", lat: 44.5711, lng: 26.0850 },
  { iata: "SOF", name: "Sofia Airport", city: "Sofia", country: "BG", lat: 42.6952, lng: 23.4114 },
  { iata: "TLV", name: "Ben Gurion Airport", city: "Tel Aviv", country: "IL", lat: 32.0114, lng: 34.8867 },
  { iata: "BEY", name: "Rafic Hariri International Airport", city: "Beirut", country: "LB", lat: 33.8209, lng: 35.4883 },
  { iata: "AMM", name: "Queen Alia International Airport", city: "Amman", country: "JO", lat: 31.7226, lng: 35.9932 },
  { iata: "RUH", name: "King Khalid International Airport", city: "Riyadh", country: "SA", lat: 24.9576, lng: 46.6988 },
  { iata: "KWI", name: "Kuwait International Airport", city: "Kuwait City", country: "KW", lat: 29.2267, lng: 47.9689 },
];

export function findAirport(iata: string): Airport | undefined {
  return AIRPORTS.find((a) => a.iata.toUpperCase() === iata.toUpperCase());
}
